version: "3.4"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres10"
    ports:
      - "5432:5432"
    volumes:
      - /Users/macbook/Dev/volumes/postgres:/var/lib/postgresql/data
    networks:
      - postgres-net
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /Users/macbook/Dev/volumes/jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
      - "50000:50000"
networks:
  postgres-net:
    driver: bridge